// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX4HbnIKNQAalO273MMoRtIYll_CIP9Ts',
    appId: '1:672322838909:web:d9160fd36f9c5d8ee22c14',
    messagingSenderId: '672322838909',
    projectId: 'gamer-s-hub-08',
    authDomain: 'gamer-s-hub-08.firebaseapp.com',
    storageBucket: 'gamer-s-hub-08.firebasestorage.app',
    measurementId: 'G-NP1XQ926V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8v6Sp-PZV03Y8dgK0YJlZw-LPiH0Nq6s',
    appId: '1:672322838909:android:753de7da823ab98de22c14',
    messagingSenderId: '672322838909',
    projectId: 'gamer-s-hub-08',
    storageBucket: 'gamer-s-hub-08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlaIW7KcYQ9VAZkf13swltRC1tYWuGY4A',
    appId: '1:672322838909:ios:a5b1edc07cc2b836e22c14',
    messagingSenderId: '672322838909',
    projectId: 'gamer-s-hub-08',
    storageBucket: 'gamer-s-hub-08.firebasestorage.app',
    iosBundleId: 'com.example.gamingstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlaIW7KcYQ9VAZkf13swltRC1tYWuGY4A',
    appId: '1:672322838909:ios:a5b1edc07cc2b836e22c14',
    messagingSenderId: '672322838909',
    projectId: 'gamer-s-hub-08',
    storageBucket: 'gamer-s-hub-08.firebasestorage.app',
    iosBundleId: 'com.example.gamingstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX4HbnIKNQAalO273MMoRtIYll_CIP9Ts',
    appId: '1:672322838909:web:e807a7e6160a86d0e22c14',
    messagingSenderId: '672322838909',
    projectId: 'gamer-s-hub-08',
    authDomain: 'gamer-s-hub-08.firebaseapp.com',
    storageBucket: 'gamer-s-hub-08.firebasestorage.app',
    measurementId: 'G-8G47XSP9F7',
  );
}
